### ISSUE TITLE
Error : Duplicate jobs requested

### ISSUE THREAD

**Issue by seqasim** [jniediek/combinato#33]
Hi,

I've been using Combinato successfully for some time. I've started getting this error recently, and I'm not sure why. I have tried this with a fresh install and environment, and I keep getting the same error now, even on data I had successfully clustered in the past. It's a hard error message to parse as this is all MATLAB data and thus should not really utilize the job pipeline? 

`Opened data_NSX001_CSS.h5
Job ('data_NSX001_CSS.h5', 'neg', 'sort_neg_sal_0000000_0000237') requested 8 times
Traceback (most recent call last):
  File "/home1/salman.qasim/Salman_Python_Scripts/combinato-master/css-cluster", line 5, in <module>
    argument_parser()
  File "/home1/salman.qasim/Salman_Python_Scripts/combinato-master/combinato/cluster/cluster.py", line 305, in argument_parser
    test_joblist(joblist)
  File "/home1/salman.qasim/Salman_Python_Scripts/combinato-master/combinato/cluster/cluster.py", line 264, in test_joblist
    raise ValueError('Duplicate jobs requested')
ValueError: Duplicate jobs requested
Job ('data_NSX001_CSS.h5', 'neg', 'sort_neg_sal_0000000_0000237') requested 8 times
Traceback (most recent call last):
  File "/home1/salman.qasim/Salman_Python_Scripts/combinato-master/css-combine", line 5, in <module>
    parse_args()
  File "/home1/salman.qasim/Salman_Python_Scripts/combinato-master/combinato/cluster/concatenate.py", line 386, in parse_args
    test_joblist(jobs)
  File "/home1/salman.qasim/Salman_Python_Scripts/combinato-master/combinato/cluster/cluster.py", line 264, in test_joblist
    raise ValueError('Duplicate jobs requested')
ValueError: Duplicate jobs requested`

**Comment by jniediek** [comment]
Hi @seqasim, happy to hear that you have been using Combinato for some time now :-)

It's possible that the problem you describe is not a bug, but related to job-files that contain the same lines several times. This happens when you start processing a folder, interrupt the processing, and then restart it. The easiest check would be to start with a fresh copy of the datafolder, with only those files that exist when you get the unclustered data. Or, you could simply delete all do_...txt files and restart.

If this doesn't solve the problem, I'll ask you to send me one of the problematic files.

**Comment by seqasim** [comment]
Hi, 

I did this. I now get this error: 

'Opened data_NSX102_CSS.h5
Starting 1 jobs with 41 workers
Writing options to file css-cluster-log.txt
Clustering data in sort_neg_sal_0000000_0002620/sort_0
failed to get the current screen resources
Traceback (most recent call last):
  File "/home1/salman.qasim/Salman_Python_Scripts/combinato-master/css-cluster", line 5, in <module>
    argument_parser()
  File "/home1/salman.qasim/Salman_Python_Scripts/combinato-master/combinato/cluster/cluster.py", line 319, in argument_parser
    pool.map(sort_helper, joblist)
  File "/home1/salman.qasim/.conda/envs/combinato/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home1/salman.qasim/.conda/envs/combinato/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
TypeError: The numpy boolean negative, the `-` operator, is not supported, use the `~` operator or the logical_not function instead.
Starting 40 workers to concatenate
Starting read from data_NSX102_CSS.h5
Working on sort_neg_sal_0000000_0002620/sorting.h5
Traceback (most recent call last):
  File "/home1/salman.qasim/Salman_Python_Scripts/combinato-master/css-combine", line 5, in <module>
    parse_args()
  File "/home1/salman.qasim/Salman_Python_Scripts/combinato-master/combinato/cluster/concatenate.py", line 405, in parse_args
    for fname, sessions in jobdict.items()])
  File "/home1/salman.qasim/.conda/envs/combinato/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home1/salman.qasim/.conda/envs/combinato/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
TypeError: 'NoneType' object has no attribute '__getitem__' '

**Comment by jniediek** [comment]
Hi, probably you switched back to an old version of the code accidentally. Try git pull in the repository folder, or download the Combinato code from github again.

I'm happy to help if it doesn't work.
