### ISSUE TITLE
Digital filter critical frequency values

### ISSUE THREAD

**Issue by YvesPauli** [jniediek/combinato#53]
Hi Johannes,
I have a problem with my combinato installation on Windows.

When I try to run
'python css-extract --files A2.ncs' (A2 being the file name of my own file)
it gives me the following error message:

File "C:\Users\PauliY\Anaconda3\lib\site-packages\scipy\signal\filter_design.py", line 2366, in iirfilter
    raise ValueError("Digital filter critical frequencies "
ValueError: Digital filter critical frequencies must be 0 < Wn < 1

I ploted the values for Wn and it seems like the first loop runs smoothly and in the second loop Wn[1] is higher than 1 (1.5 to be exact).

Any help is appreciated, thank you.
Yves

**Comment by jniediek** [comment]
Hi Yves,

It would be helpful to see more lines of the error message. I can only guess that the error is generated either this line of code:

https://github.com/jniediek/combinato/blob/80fec280699250304e7c58fa0fec0a4e2faaabb4/combinato/extract/mp_extract.py#L82

or in this line of code:

https://github.com/jniediek/combinato/blob/80fec280699250304e7c58fa0fec0a4e2faaabb4/combinato/extract/tools.py#L57

In both cases, I suspect the argument of `DefaultFilter` to be wrong. It is supposed to be the time between two samples in seconds. For example, if your sampling rate is 32 kHz, then the argument of `DefaultFilter` should be 1/32000 = 3.125e-05.

**Comment by YvesPauli** [comment]
Hi Johannes,

Here is the whole output in my powershell window after executing the css-extract command:

PS C:\Users\PauliY\Anaconda3\Lib\site-packages\combinato-master> python css-extract --files A2.ncs
A2
Wn =  [0.15 0.5 ]
Wn =  [0.15 1.5 ]
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\PauliY\Anaconda3\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\PauliY\Anaconda3\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\PauliY\Anaconda3\Lib\site-packages\combinato-master\combinato\extract\mp_extract.py", line 141, in read
    openfiles[jname] = ExtractNcsFile(job['filename'], job['reference'])
  File "C:\Users\PauliY\Anaconda3\Lib\site-packages\combinato-master\combinato\extract\tools.py", line 57, in __init__
    self.filter = DefaultFilter(self.ncs_file.timestep)
  File "C:\Users\PauliY\Anaconda3\Lib\site-packages\combinato-master\combinato\basics\filters.py", line 30, in __init__
    self.c_extract = ellip(2, .1, 40,
  File "C:\Users\PauliY\Anaconda3\lib\site-packages\scipy\signal\filter_design.py", line 3244, in ellip
    return iirfilter(N, Wn, rs=rs, rp=rp, btype=btype, analog=analog,
  File "C:\Users\PauliY\Anaconda3\lib\site-packages\scipy\signal\filter_design.py", line 2366, in iirfilter
    raise ValueError("Digital filter critical frequencies "
ValueError: Digital filter critical frequencies must be 0 < Wn < 1

After this I have to forcibly interrupt the process.

Regarding your answer, should I manually input the argument as the desired value? As of now the values are imported from the .ncs files which of course makes more sense in case of differing measurements.

Yves

**Comment by YvesPauli** [comment]
The problem was not with the installation or the code.
The files were recorded with macro-wires instead of micro-wires resulting in a sampling frequency which is too low.
With the correct files the error does not come up.
Thank you
