### ISSUE TITLE
Error when running on personal data

### ISSUE THREAD

**Issue by botwithabeard** [jniediek/combinato#56]
Hi,

I have successfully installed combinato on my Laptop and have completed the first part of the tutorial using the data provided, but when I run css-extract --matfile myfile.mat it gives the following error:

```bash
(base) C:\Users\Name\Desktop\combinato>python css-extract --matfile data_matlab_corrected.mat
Reading from matfile data_matlab_corrected.mat
Using default sampling rate (24.0 kHz)
Process Process-1:
Traceback (most recent call last):
  File "D:\anaconda3\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "D:\anaconda3\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Name\Desktop\combinato\combinato\extract\mp_extract.py", line 130, in read
    data = read_matfile(fname)
  File "C:\Users\Name\Desktop\combinato\combinato\extract\tools.py", line 31, in read_matfile
    fdata = data['data'].ravel()
KeyError: 'data'
```

I even checked the format of my data with the sample data provided for the tutorial and it's double type and the data is [channel x time]

Any Advice on how to move forward?
Thank you.

**Comment by jniediek** [comment]
Hi,

from the error message you provided I would guess that your data variable is not called data?

Johannes
