### ISSUE TITLE
How can you run css-mask-artifacts with all files?

### ISSUE THREAD

**Issue by dustinf1989** [jniediek/combinato#70]
I am trying to use the following command in Windows 10:

`python css-mask-artifacts --concurrent-file sort_pos_drd.txt`

where sort_pos_drd.txt is a file containing

```
uAHL1_0003\data_uAHL1_0003.h5 pos uAHL1_0003\sort_pos_drd
uAHL2_0003\data_uAHL2_0003.h5 pos uAHL2_0003\sort_pos_drd
uAHL3_0003\data_uAHL3_0003.h5 pos uAHL3_0003\sort_pos_drd
uAHL4_0003\data_uAHL4_0003.h5 pos uAHL4_0003\sort_pos_drd
```

> Traceback (most recent call last):
>   File "C:\Users\drdus\Documents\Python\combinato\css-mask-artifacts", line 5, in <module>
>     parse_args()
>   File "C:\Users\drdus\Documents\Python\combinato\combinato\artifacts\mask_artifacts.py", line 319, in parse_args
>     bincount_to_edges(conc_fname)
>   File "C:\Users\drdus\Documents\Python\combinato\combinato\artifacts\mask_artifacts.py", line 162, in bincount_to_edges
>     conc_fid = tables.open_file(concurrent_fname, 'r')
>   File "C:\Users\drdus\anaconda3\lib\site-packages\tables\file.py", line 315, in open_file
>     return File(filename, mode, title, root_uep, filters, **kwargs)
>   File "C:\Users\drdus\anaconda3\lib\site-packages\tables\file.py", line 778, in __init__
>     self._g_new(filename, mode, **params)
>   File "tables/hdf5extension.pyx", line 492, in tables.hdf5extension.File._g_new
> tables.exceptions.HDF5ExtError: HDF5 error back trace
> 
>   File "C:\ci\hdf5_1593121603621\work\src\H5F.c", line 509, in H5Fopen
>     unable to open file
>   File "C:\ci\hdf5_1593121603621\work\src\H5Fint.c", line 1652, in H5F_open
>     unable to read superblock
>   File "C:\ci\hdf5_1593121603621\work\src\H5Fsuper.c", line 420, in H5F__super_read
>     file signature not found
> 
> End of HDF5 error back trace
> 
> Unable to open/create file 'sort_pos_drd.txt'

I have a file named 'do_extract.txt' containing

```
D:\data\uAHL1_0003.ncs
D:\data\uAHL2_0003.ncs
D:\data\uAHL3_0003.ncs
D:\data\uAHL4_0003.ncs
```

Which I was able to run using

`python css-extract --jobs D:\data\to_extract.txt`

but I can't get any of the subsequent functions to run batch processings from a txt file.

**Comment by dustinf1989** [comment]
So it seems that I can just run `python css-mask-artifacts` and it runs the artifact detection on all files in the local combination path. I then would like to do css-cluster on a job file, but it doesn't work. In fact, css-cluster doesn't work for even a single file (css-simple-cluster does though). I tried the same thing on 2 different computers, once after freshly installing Combinato and it doesn't work on either one.

> `python css-cluster --jobs do_cluster_job.txt`
```
[Starting 2 jobs with 13 workers
Writing options to file css-cluster-log.txt
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "\anaconda3\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "\anaconda3\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "\combinato\combinato\cluster\cluster.py", line 224, in sort_helper
    main(args[0], args[2], args[1], options['overwrite'])
IndexError: tuple index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "\combinato\css-cluster", line 5, in <module>
    argument_parser()
  File "\combinato\combinato\cluster\cluster.py", line 320, in argument_parser
    pool.map(sort_helper, joblist)
  File "\anaconda3\lib\multiprocessing\pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "\anaconda3\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
IndexError: tuple index out of range](url)
```

**Comment by dustinf1989** [comment]
I found out that if your files do not begin with CSC that you can change this function in combinato/util/tools.py

You can uncomment some lines if you want to make sure the code is working for you or just delete them.

```
def h5files(path):
    """
    highly specific tool to find all relevant h5 files
    if their names follow the CSC?, CSC?? naming convention
    """
    def sort_function(fname):
        # This function sorts files based on patterns data_CSC?????? and removes .h5 from the end
        # Why is it necessary?
        try:
            # a = int(os.path.basename(fname)[8:-3]) # For data_CSC????
            a = int(os.path.basename(fname)) # DF added: For anything
            print(a)
            return a
        except ValueError:
            return fname

    # channel_dirs = glob(os.path.join(path, 'CSC?')) # Why was this commented?
    # channel_dirs += glob(os.path.join(path, 'CSC??'))
     
    channel_dirs = [] # Get patterns based on the options file
    for pat in options['folder_patterns']:
        channel_dirs += glob(os.path.join(path, pat))
        
    # print(path)
    # print(channel_dirs)

    ret = []
    for chd in channel_dirs:
        basename = os.path.basename(chd)
        h5cand = os.path.join(chd, 'data_{}.h5'.format(basename))
        # print(h5cand, os.path.exists(h5cand))
        if os.path.exists(h5cand):
            # print(h5cand, os.stat(h5cand).st_size)
            if os.stat(h5cand).st_size > 0:
                # print('yes', os.stat(h5cand).st_size)
                ret.append(h5cand)
    # print(ret)
    # print(sort_function)
    # print(sorted(ret, key=sort_function))
    return sorted(ret, key=sort_function)****
```
